name: Scrape Talk Locations

on:
  push:
    paths:
      - 'talks/**'
      - '_talks/**'
      - 'talkmap.ipynb'

# 显式给 GITHUB_TOKEN 写权限（很关键）
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # 推荐，便于查看历史/分支等

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install jupyter pandas requests beautifulsoup4 geopy
          pip install getorg --upgrade

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

      - name: Commit and push changes
        env:
          # CHECK: GITHUB_TOKEN 自动由 Actions 提供，无需在 secrets 中配置
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update of talk locations" || echo "No changes to commit"
          git push origin HEAD:main
